---
# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rto-rpo-data
  namespace: ramen-test
  labels:
    app: rto-rpo-test
    appname: rto-rpo-test
    ramendr.openshift.io/protected: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: harvester-longhorn
  resources:
    requests:
      storage: 1Gi
